### ISSUE TITLE
Can not install tiff-multipage with npm install tiff-multipage

### ISSUE THREAD

**Issue by honeyonsys** [blackbeam/tiff-multipage#1]
npm install tiff-multipage

> tiff-multipage@0.1.2 install E:\laragon\www\tiffmerge\node_modules\tiff-multipage
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\laragon\bin\nodejs\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\laragon\bin\nodejs\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at E:\laragon\bin\nodejs\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "E:\\laragon\\bin\\nodejs\\node.exe" "E:\\laragon\\bin\\nodejs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\laragon\www\tiffmerge\node_modules\tiff-multipage
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN tiffmerge@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiff-multipage@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiff-multipage@0.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\harish\AppData\Roaming\npm-cache\_logs\2017-09-14T07_13_22_841Z-debug.log

**Comment by blackbeam** [comment]
Hi!
Package is not tested on the windows platform and may not work on it.
AFAICS the build procedure errors because `python` is not in `PATH`. Is it installed? Is it in `PATH` variable?
Or you can specify it in `PYTHON` variable like this:

```cmd
set "PYTHON=C:\your\path\to\the\python\executable"
npm install tiff-multipage
```

Also note that `tiff-multipage` depends on `libtiff`. So `libtiff` and its development headers must be available to the node's build system (i'm not sure on how exactly it should work on Windows).

**Comment by honeyonsys** [comment]
No the python was not installed. I have just install it now.

**Comment by honeyonsys** [comment]
After install python i have tried this
set "PYTHON=C:\Users\harish\AppData\Local\Programs\Python\Python36-32\python.exe"
npm install tiff-multipage

and getting this error:



> tiff-multipage@0.1.2 install E:\tiffmerge\node_modules\tiff-multipage
> node-gyp rebuild


E:\tiffmerge\node_modules\tiff-multipage>if not defined npm_config_node_gyp (node "E:\laragon\bin\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Users\harish\AppData\Local\Programs\Python\Python36-32\python.exe" is v3.6.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (E:\laragon\bin\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at E:\laragon\bin\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "E:\\laragon\\bin\\nodejs\\node.exe" "E:\\laragon\\bin\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\tiffmerge\node_modules\tiff-multipage
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN tiffmerge@1.0.0 No description
npm WARN tiffmerge@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "E:\\laragon\\bin\\nodejs\\node.exe" "E:\\laragon\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "tiff-multipage"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! tiff-multipage@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiff-multipage@0.1.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tiff-multipage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tiff-multipage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tiff-multipage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\tiffmerge\npm-debug.log

**Comment by blackbeam** [comment]
As you can see your python version is to new for node-gyp.
It requires Python >= v2.5.0 & < v3.0.0. But you have python v3.6.2.

**Comment by honeyonsys** [comment]
installed python 2.7.13, then 

set "PYTHON=c:\Python27\python.exe"
npm install tiff-multipage


and got this error:

> tiff-multipage@0.1.2 install E:\tiffmerge\node_modules\tiff-multipage
> node-gyp rebuild


E:\tiffmerge\node_modules\tiff-multipage>if not defined npm_config_node_gyp (node "E:\laragon\bin\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
'pkg-config' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'pkg-config --libs libtiff-4' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (E:\laragon\bin\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "E:\\laragon\\bin\\nodejs\\node.exe" "E:\\laragon\\bin\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\tiffmerge\node_modules\tiff-multipage
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN tiffmerge@1.0.0 No description
npm WARN tiffmerge@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "E:\\laragon\\bin\\nodejs\\node.exe" "E:\\laragon\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "tiff-multipage"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! tiff-multipage@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiff-multipage@0.1.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tiff-multipage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tiff-multipage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tiff-multipage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\tiffmerge\npm-debug.log

**Comment by blackbeam** [comment]
I'll try to find time to add windows-related changes to `binding.gyp`.

You can build libtiff or try to find it prebuilt for your architecture (32 or 64 bit) while waiting.
For build instructions see **Building the Software under Windows 2000/XP/7/8/10 with nmake** section [here](http://www.simplesystems.org/libtiff/build.html).

**Comment by honeyonsys** [comment]
ok I am waiting for you to finish this. In the mean time i try to build libtiff

**Comment by blackbeam** [comment]
I've just published v0.1.3.
It requires that all libtiff headers as well as libtiff.lib to be in `.\deps\libtiff\`.

```
c:\ > dir deps\libtiff
 Volume in drive C has no label.
 Volume Serial Number is 383B-8239

 Directory of C:\Users\set\Desktop\tmp1\deps\libtiff

17.09.2017  13:43    <DIR>          .
17.09.2017  13:43    <DIR>          ..
17.09.2017  13:43           747 902 libtiff.lib
17.09.2017  13:43            35 860 libtiff_i.lib
17.09.2017  13:43            11 379 t4.h
17.09.2017  13:43            35 983 tiff.h
17.09.2017  13:43             3 902 tiffconf.h
17.09.2017  13:43             3 902 tiffconf.vc.h
17.09.2017  13:43             3 346 tiffconf.wince.h
17.09.2017  13:43            23 227 tiffio.h
17.09.2017  13:43            18 408 tiffiop.h
17.09.2017  13:43               410 tiffvers.h
17.09.2017  13:43             3 147 tif_config.h
17.09.2017  13:43             3 147 tif_config.vc.h
17.09.2017  13:43             1 852 tif_config.wince.h
17.09.2017  13:43            10 918 tif_dir.h
17.09.2017  13:43            16 413 tif_fax3.h
17.09.2017  13:43             2 964 tif_predict.h
17.09.2017  13:43             5 641 uvcode.h
              17 File(s)        928 401 bytes
               2 Dir(s)   5 956 071 424 bytes free

c:\ > npm install tiff-multipage

> tiff-multipage@0.1.3 install C:\Users\set\Desktop\tmp1\node_modules\tiff-multipage
> node-gyp rebuild

C:\Users\set\Desktop\tmp1\node_modules\tiff-multipage>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  module.cc
  sync.cc
  async.cc
  tiff_multipage.cc
..\src\tiff_multipage.cc(50): warning C4244: '=': conversion from 'tmsize_t' to 'int32_t', possible loss of data [C:\Users\set\Desktop\tmp1\node_modules\tiff-multipage\build\
tiff-multipage.vcxproj]
  win_delay_load_hook.cc
     Creating library C:\Users\set\Desktop\tmp1\node_modules\tiff-multipage\build\Release\tiff-multipage.lib and object C:\Users\set\Desktop\tmp1\node_modules\tiff-multipage\
  build\Release\tiff-multipage.exp
  Generating code
  Finished generating code
  tiff-multipage.vcxproj -> C:\Users\set\Desktop\tmp1\node_modules\tiff-multipage\build\Release\\tiff-multipage.node
  tiff-multipage.vcxproj -> C:\Users\set\Desktop\tmp1\node_modules\tiff-multipage\build\Release\tiff-multipage.pdb (Full PDB)
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\set\Desktop\tmp1\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\set\Desktop\tmp1\package.json'
npm WARN tmp1 No description
npm WARN tmp1 No repository field.
npm WARN tmp1 No README data
npm WARN tmp1 No license field.

+ tiff-multipage@0.1.3
updated 1 package in 7.317s

c:\ > node
> require('tiff-multipage')
{ joinAsync: [Function], joinSync: [Function] }
>
```

**Comment by honeyonsys** [comment]
i have tried to install it show me this


> tiff-multipage@0.1.3 install F:\laragon\www\tifftomultipage\node_modules\tiff-multipage
> node-gyp rebuild


F:\laragon\www\tifftomultipage\node_modules\tiff-multipage>if not defined npm_config_node_gyp (node "F:\laragon\bin\nodejs\node-v6.11.0-x64\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (F:\laragon\bin\nodejs\node-v6.11.0-x64\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "F:\\laragon\\bin\\nodejs\\node-v6.11.0-x64\\node.exe" "F:\\laragon\\bin\\nodejs\\node-v6.11.0-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\laragon\www\tifftomultipage\node_modules\tiff-multipage
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN tiffmerge@1.0.0 No description
npm WARN tiffmerge@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "F:\\laragon\\bin\\nodejs\\node-v6.11.0-x64\\node.exe" "F:\\laragon\\bin\\nodejs\\node-v6.11.0-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "tiff-multipage" "--save"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! tiff-multipage@0.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiff-multipage@0.1.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tiff-multipage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tiff-multipage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tiff-multipage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\laragon\www\tifftomultipage\npm-debug.log

**Comment by blackbeam** [comment]
Did you install visual studio? Which version? I'm using visual studio express.

You could also try this to install build-tools:
> open up a new cmd as administrator and run this command:
`npm install --global --production windows-build-tools`
then
`npm config set msvs_version 2015 --global`
close all instances of shell/cmd, reopen a cmd (regular this time, non-administrator) return to your directory where you are trying to run npm install and run it again

**Comment by honeyonsys** [comment]
ok, do i have to install both visual studio and windows build tools or it can be done by installing only windows-build-tools?

i have already run this command npm install --global --production windows-build-tools
and its taking too much time to install after python installation

**Comment by blackbeam** [comment]
> do i have to install both visual studio and windows build tools or it can be done by installing only windows-build-tools?

I think one of this two options should be enough.
I've installed visual studio and worked in **x64 Native Tools Command Prompt for VS 2017** after that (may be found in Start menu after visual studio express installation).
I did both libtiff compilation and tiff-multipage installation in this command prompt without issues.

> i have already run this command npm install --global --production windows-build-tools
and its taking too much time to install

Build tools are huge so it should be ok.

**Comment by honeyonsys** [comment]
ok i have installation process for visual studio express 2017 on my one device and windows-build-tools on another. Will test both and put my reviews here :)

**Comment by blackbeam** [comment]
Good luck)

**Comment by honeyonsys** [comment]
After installing window-build-tools i got this now

 npm install tiff-multipage --save

> tiff-multipage@0.1.3 install F:\laragon\www\tifftomultipage\node_modules\tiff-multipage
> node-gyp rebuild


F:\laragon\www\tifftomultipage\node_modules\tiff-multipage>if not defined npm_config_node_gyp (node "F:\laragon\bin\nodejs\node-v6.11.0-x64\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  module.cc
  sync.cc
  async.cc
  tiff_multipage.cc
f:\laragon\www\tifftomultipage\node_modules\tiff-multipage\src\tiff_multipage.h(27): fatal error C1083: Cannot open inc
lude file: 'tiffio.h': No such file or directory (compiling source file ..\src\tiff_multipage.cc) [F:\laragon\www\tifft
omultipage\node_modules\tiff-multipage\build\tiff-multipage.vcxproj]
  win_delay_load_hook.cc
f:\laragon\www\tifftomultipage\node_modules\tiff-multipage\src\tiff_multipage.h(27): fatal error C1083: Cannot open inc
lude file: 'tiffio.h': No such file or directory (compiling source file ..\src\sync.cc) [F:\laragon\www\tifftomultipage
\node_modules\tiff-multipage\build\tiff-multipage.vcxproj]
f:\laragon\www\tifftomultipage\node_modules\tiff-multipage\src\tiff_multipage.h(27): fatal error C1083: Cannot open inc
lude file: 'tiffio.h': No such file or directory (compiling source file ..\src\async.cc) [F:\laragon\www\tifftomultipag
e\node_modules\tiff-multipage\build\tiff-multipage.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (F:\laragon\bin\nodejs\node-v6.11.0-x64\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "F:\\laragon\\bin\\nodejs\\node-v6.11.0-x64\\node.exe" "F:\\laragon\\bin\\nodejs\\node-v6.11.0-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\laragon\www\tifftomultipage\node_modules\tiff-multipage
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN tiffmerge@1.0.0 No description
npm WARN tiffmerge@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "F:\\laragon\\bin\\nodejs\\node-v6.11.0-x64\\node.exe" "F:\\laragon\\bin\\nodejs\\node-v6.11.0-x64\\node_modules\\npm\\bin\\npm-cli.js" "install" "tiff-multipage" "--save"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! tiff-multipage@0.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiff-multipage@0.1.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tiff-multipage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tiff-multipage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tiff-multipage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\laragon\www\tifftomultipage\npm-debug.log

**Comment by blackbeam** [comment]
Do you have `deps` directory in the current working directory (where you executing `npm install tiff-multipage`)? (see [this comment](https://github.com/blackbeam/tiff-multipage/issues/1#issuecomment-330038561) about requirements on libtiff lib and headers)

What is the output of `dir deps\libtiff` command?

**Comment by honeyonsys** [comment]
no there is no deps/libtiff directory under my application folder. How can i get that?
i am running >npm install tiff-multipage under my application folder

**Comment by blackbeam** [comment]
You need to build libtiff (see [this comment](https://github.com/blackbeam/tiff-multipage/issues/1#issuecomment-329455865)). Then you need to copy resulting `libtiff.lib` file as well as every `*.h` files to the `deps/libtiff` directory in your project root.

**Comment by honeyonsys** [comment]
with the deps you mean dependencies/node_modules?

**Comment by blackbeam** [comment]
> with the deps you mean dependencies/node_modules?

I literaly mean `.\deps\libtiff\` directory in the root of your nodejs project.

`dir .\deps\libtiff\` command runned in the root of your nodejs project should return something like this:

```cmd
c:\your\nodejs\project\root > dir deps\libtiff
 Volume in drive C has no label.
 Volume Serial Number is 383B-8239

 Directory of C:\your\nodejs\project\root\deps\libtiff

17.09.2017  13:43    <DIR>          .
17.09.2017  13:43    <DIR>          ..
17.09.2017  13:43           747 902 libtiff.lib
17.09.2017  13:43            11 379 t4.h
17.09.2017  13:43            35 983 tiff.h
17.09.2017  13:43             3 902 tiffconf.h
17.09.2017  13:43             3 902 tiffconf.vc.h
17.09.2017  13:43             3 346 tiffconf.wince.h
17.09.2017  13:43            23 227 tiffio.h
17.09.2017  13:43            18 408 tiffiop.h
17.09.2017  13:43               410 tiffvers.h
17.09.2017  13:43             3 147 tif_config.h
17.09.2017  13:43             3 147 tif_config.vc.h
17.09.2017  13:43             1 852 tif_config.wince.h
17.09.2017  13:43            10 918 tif_dir.h
17.09.2017  13:43            16 413 tif_fax3.h
17.09.2017  13:43             2 964 tif_predict.h
17.09.2017  13:43             5 641 uvcode.h
              16 File(s)        928 401 bytes
               2 Dir(s)   5 956 071 424 bytes free
```

**Comment by honeyonsys** [comment]
it return

 dir deps\libtiff
The system cannot find the file specified.

**Comment by blackbeam** [comment]
You must create this directory and copy compiled `libtiff.lib` and all libtiff headers to it.

**Comment by honeyonsys** [comment]
have created deps\libtiff into root and copy all the libtiff folder's files into it. But i dont have libtiff.lib file.
Can you send me a link to download all the files

**Comment by blackbeam** [comment]
I don't have links to prebuilt binaries, but you can try to google it yourself but note that they may not work on your platform.

I think it is easyer for you to compile it yourself because procedure is trivial. libtiff source distribution is located [here](http://download.osgeo.org/libtiff/tiff-4.0.8.zip) and the build instructions (which is simply two commands) is [here](http://www.simplesystems.org/libtiff/build.html#PC).

Just search the tiff distribution directory for the compiled `libtiff.lib` after build procedure completes.

**Comment by litemikx** [comment]
I'm able to build the libtiff source code, had the files in a directory /deps/libtiff. But I'm still getting error when installing. 

I'm getting 12 unresolved externals like this:

`tiff_multipage.obj : error LNK2001: unresolved external symbol _TIFFmalloc [D:\github\hl7-pdf-to-img-handler-v3\node_modules\tiff-multipage\build\tif
f-multipage.vcxproj]`

**Comment by blackbeam** [comment]
@LightDev777, hi.
Looks like something wrong with your build of libtiff, since _TIFFmalloc is essential symbol of this library. I'm not sure, however, what's wrong. Try to look into libtiff.lib and see which symbols are exported.

**Comment by litemikx** [comment]
Nevermind on my end, I was able to build mine. Can't remember though how. But I downloaded the latest libtiff 4.0.9, then followed this one: [How to Build Libtiff on Windows](http://www.simplesystems.org/libtiff/build.html#PC). I guess issue was something related to the windows build tools and the current setup on the machine.
